// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxniw2woHSI7q9uHG1p1Td60kKdPX3vI',
    appId: '1:38596047061:web:3cf46d8ef2c43e0663b25c',
    messagingSenderId: '38596047061',
    projectId: 'di-dong-nang-cao',
    authDomain: 'di-dong-nang-cao.firebaseapp.com',
    storageBucket: 'di-dong-nang-cao.firebasestorage.app',
    measurementId: 'G-QVNL61TR6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjndW6sYbbHZKDOnYLsF8M5uOV_BdZ4HA',
    appId: '1:38596047061:android:e5a9a2d938b016a263b25c',
    messagingSenderId: '38596047061',
    projectId: 'di-dong-nang-cao',
    storageBucket: 'di-dong-nang-cao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUKmSc_sQayN4qzas_SimEgq8Q1n97RE',
    appId: '1:38596047061:ios:bf2090cf2e13665d63b25c',
    messagingSenderId: '38596047061',
    projectId: 'di-dong-nang-cao',
    storageBucket: 'di-dong-nang-cao.firebasestorage.app',
    iosBundleId: 'com.example.doAnLtddnc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBUKmSc_sQayN4qzas_SimEgq8Q1n97RE',
    appId: '1:38596047061:ios:bf2090cf2e13665d63b25c',
    messagingSenderId: '38596047061',
    projectId: 'di-dong-nang-cao',
    storageBucket: 'di-dong-nang-cao.firebasestorage.app',
    iosBundleId: 'com.example.doAnLtddnc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxniw2woHSI7q9uHG1p1Td60kKdPX3vI',
    appId: '1:38596047061:web:204e423ea0220d5f63b25c',
    messagingSenderId: '38596047061',
    projectId: 'di-dong-nang-cao',
    authDomain: 'di-dong-nang-cao.firebaseapp.com',
    storageBucket: 'di-dong-nang-cao.firebasestorage.app',
    measurementId: 'G-FZM2CM6NL6',
  );
}
